### ISSUE TITLE
Segfault from km client if workflow is not responsive

### ISSUE THREAD

**Issue by bls** [bsycorp/keymaster#20]
```
time="2021-06-10T00:08:24Z" level=info msg="error calling workflowApi.GetAssertions: workflow getassertions error: http error: server error: StatusCode: 504: Body: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9f1115]
goroutine 1 [running]:
github.com/bsycorp/keymaster/cmd/km/commands.runWorkflow(0xc000072840, 0xc0004ca410, 0xc000023110, 0x25, 0x0, 0x0, 0x0)
	/builds/keymaster/keymaster/keymaster/cmd/km/commands/ci.go:182 +0x685
github.com/bsycorp/keymaster/cmd/km/commands.ci(0x11293a0, 0xc0001cac00, 0x0, 0x10)
	/builds/keymaster/keymaster/keymaster/cmd/km/commands/ci.go:91 +0x24b
github.com/spf13/cobra.(*Command).execute(0x11293a0, 0xc0001ca900, 0x10, 0x10, 0x11293a0, 0xc0001ca900)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1129b20, 0x441f0a, 0x10ec8a0, 0xc000054778)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/bsycorp/keymaster/cmd/km/commands.Execute()
	/builds/keymaster/keymaster/keymaster/cmd/km/commands/root.go:29 +0x31
main.main()
	/builds/keymaster/keymaster/keymaster/cmd/km/main.go:11 +0x20
```

**Comment by bls** [comment]
504 should be handled properly and result in more retries.
